<?php
pll_register_string('Artistes Bio', 'Biographie', 'Artistes');
pll_register_string('Artistes Presse', 'Presse', 'Artistes');
pll_register_string('Liste', 'Liste', 'Artistes & Expositions');
pll_register_string('Artistes', 'Vous aimerez aussi', 'Artistes');
pll_register_string('Artistes', 'Contactez nous','Artistes');
pll_register_string('Bibliographie', 'Bibliographie', 'Artistes');
pll_register_string('Artistes Title', 'Artistes', 'Artistes & Expositions');
pll_register_string('Thumbnails', 'Vignettes', 'Artistes & Expositions');
pll_register_string('Details', 'Details', 'Artistes & Expositions');
pll_register_string('Works', 'Oeuvres', 'Artistes & Expositions');
pll_register_string('Publications', 'Publications', 'Artistes & Expositions');
pll_register_string('Exposition singulier', 'Exposition', 'Expositions');
pll_register_string('Exposition Press', 'Informations', 'Exposnfions');
pll_register_string('Exposition Current', 'Actuellement', 'Expositions');
pll_register_string('Exposition Past', 'Passé', 'Expositions');
pll_register_string('Exposition Upcoming', 'A venir', 'Expositions');
pll_register_string('Foires Title', 'Foires et Salons', 'Foires');
pll_register_string('Tour virtuel', 'Tour Virtuel', 'Foires');
pll_register_string('Filtre title', 'Toutes', 'Global');
pll_register_string('PDF', 'Telecharger la publication en PDF','Global');
pll_register_string('PDF', 'Telecharger la presse','Global');
pll_register_string('PDF', 'Telecharger le dossier de presse en PDF','Global');
pll_register_string('Link', 'Lire la publication en ligne','Global');
pll_register_string('Search', 'Resultats de recherche pour ','Global');
pll_register_string('Search', 'Désolé, nous n’avons rien trouvé','Global');
pll_register_string('Footer', 'Mentions légales','Global');
